query getBillingProducts($dojoSlug: String!) {
  products: getBillingProducts(dojoSlug: $dojoSlug) {
    id
    name
    plans {
      id
      nickname
      interval
      interval_count
      amount
      currency
    }
  }
}

mutation addProduct($dojoSlug: String!) {
  newBillingProduct(dojoSlug: $dojoSlug, name: "Something 2") {
    id
    name
  }
}

mutation deleteProduct {
  deleteBillingProduct(dojoSlug: "firewall", product: "prod_EeFw0bazDHQGLm") {
    result
    message
  }
}

mutation deletePlan {
  deletePlan(dojoSlug: "firewall", plan: "plan_EeFxXZcdtb7Us9") {
    result
    message
  }
}

mutation {
  addStudentSubscription(
    dojoSlug: "firewall"
    student: "cus_EeFuv7J3eXjqtk"
    plan: "plan_EeNvLHViqRI04T"
  ) {
    result
    message
  }
}

query {
  listStudentSubscriptions(
    dojoSlug: "firewall"
    student: "cus_EeFuv7J3eXjqtk"
  ) {
    id
    created
  }
}

mutation {
  deleteStudentSubscription(dojoSlug: "firewall", plan: "sub_EePtZDAZ5vBuP7") {
    result
    message
  }
}
